[tool.poetry]
name = "opengolf"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.0.0"    # IPython 8.x supports Python 3.10
diffusers = "^0.32.2"
torch = "^2.6.0"
transformers = "^4.49.0"
accelerate = "^1.4.0"
protobuf = "^5.29.3"
sentencepiece = "^0.2.0"
openai = "^1.64.0"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
